DataModeling :
    SupervisedLearning :
        Convex :
        DecisionTree : False
        LinearRegression : 
        LogisticRegression : False
        MultinomialLogisticRegression : False
        NaiveBayesClassification : False
        RandomForest : False
        SupportVectorMachines : False
    UnsupervisedLearning : 
        kMeansClustering : False
        AssociationRules : False
        ParallelLatentDirichletAllocation : False
InferentialStatistics :
    HypothesisTests : False
Common :
